name: Voting App CI

on:
  push:
    branches:
      - main

jobs:
  build-vote:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Vote Image
        run: docker build -t vote-app ./vote

  build-result:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Result Image
        run: docker build -t result-app ./result

  build-worker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Worker Image
        run: docker build -t worker-app ./worker